"""Section 14 — Reasoning Path [EXISTS — new narrative renderer]

One paragraph per query, generated by TEMPLATE (never an LLM) so it
regenerates byte-identical from the same trace every time — verification
requirement in the brief.
"""
from __future__ import annotations


def render_reasoning_path(trace) -> str:
    n_sub = len(trace.expanded_queries)
    n_candidates = len(trace.retrieved)
    n_survived = len(trace.reranked)
    n_dropped_evidence = sum(
        1 for e in trace.evidence if e.get("nli_label") != "entailment")
    contradiction_txt = (f"{len(trace.contradictions)} contradiction(s) found"
                        if trace.contradictions else "no contradictions")
    conf = trace.confidence
    conf_txt = f"{conf:.2f}" if conf is not None else "n/a"
    bd = trace.confidence_breakdown or {}
    bd_txt = ", ".join(f"{k}={v:.2f}" for k, v in bd.items())
    locations = sorted({f"{c.get('page_url', '?')} §{c.get('chunk_id', '?')}"
                        for c in trace.citations})
    loc_txt = " and ".join(locations) if locations else "no surviving citation"

    return (
        f"Question: \"{trace.query}\" → "
        f"intent: {(trace.intent or {}).get('category', 'unknown')} → "
        f"expanded to {n_sub} sub-quer{'y' if n_sub == 1 else 'ies'} → "
        f"{n_candidates} candidate{'s' if n_candidates != 1 else ''} retrieved → "
        f"{n_survived} survived rerank → "
        f"{n_dropped_evidence} dropped (no evidence) → "
        f"{contradiction_txt} → "
        f"confidence {conf_txt} ({bd_txt}) → "
        f"answered from {loc_txt}."
    )


def render_all(traces: list) -> list[dict]:
    return [{"query": t.query, "narrative": render_reasoning_path(t)} for t in traces]
